cart_app/urls.py
from django.urls import path
from .import views
app_name='cart_app'
urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

search_app/urls.py
from django.urls import path
from .import views
app_name="search_app"
urlpatterns = [
    path('',views.Searchresult,name='Searchresult'),
]

shopapp/urls.py
from django.urls import path
from .import views
app_name='shopapp'
urlpatterns = [
    path('',views.allProCat,name='allProCat'),
    path('<slug:c_slug>/',views.allProCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='prodCatdetail'),
]

shopproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include ('shopapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static (settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static (settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart_app/models.py
from django.db import models
from shopapp.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)
    
class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return '{}'.format(self.product)



        

search_app/models.py
from django.db import models

# Create your models here.

shopapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category (models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    def get_url(self):
        return reverse('shopapp:products_by_category',args=[self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return '{}'.format(self.name)
    

    
    
class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shopapp:prodCatdetail', args=[self.category.slug ,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)
    

    





    

cart_app/views.py
from django.shortcuts import get_object_or_404, redirect, render
from shopapp.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

# Corrected function to retrieve or create a cart ID
def _cart_id(request):
    cart = request.session.get('cart_id')
    if not cart:
        cart = request.session.session_key
        if not cart:
            cart = request.session.create()
        request.session['cart_id'] = cart
    return cart

# View to add a product to the cart
def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart(cart_id=_cart_id(request))
        cart.save()
    
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem(product=product, quantity=1, cart=cart)
        cart_item.save()

    return redirect('cart_app:cart_detail')

# View to display cart details
def cart_detail(request):
    total = 0
    counter = 0
    cart_items = None

    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    return render(request, 'cart.html', {'cart_items': cart_items, 'total': total, 'counter': counter})

# View to remove a product to the cart
def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity >1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart_app:cart_detail')

# View to delete a product to the cart
def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart_app:cart_detail')

search_app/views.py
from django.shortcuts import render
from shopapp.models import Product
from django.db.models import Q
# Create your views here.

def Searchresult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query)|Q(description__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

shopapp/views.py
from django.shortcuts import get_object_or_404, render
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.


def allProCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug != None:
        c_slug=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_slug,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
        
    return render(request,"category.html",{'category':c_slug,'products':products})


def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render (request,'product.html',{'product':product})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %}  {% endblock %} ">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/coustm.css'%}"rel="stylesheet">
    <script src="https://kit.fontawesome.com/4aded11b87.js" crossorigin="anonymous"></script>

    <title>{% block title %}{% endblock %}</title>

</head>
<body>
    <div class="container">
        {% include "header.html" %}
        {% include "nav.html" %}
        {% block content %}
        {% endblock %}
    </div>
        {% include "footer.html" %}
        <script src="{% static 'js/popper.min.js'%}"></script>
        <script src="{% static 'js/bootstrap.min.js'%}"></script>
    
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
This is the CART PAGE .proceed to review your items and place the order
{% endblock %}
{% block title %}
    CART shopy company PVT LTD
{% endblock %}
{% block content%}

{% if not cart_items    %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title" > Your Shopping Cart is empty</h1>
            <br>
            <p class ="text-center">
                Please Click <a href="{% url 'shopapp:allProCat'%}"> Here to continue shopping</a>
            </p>  
        </div>
    </div>
    {% else %}
    <div>
        <div class="text-center">
            <br>
                <h1 class="text-center my-title">
                    Your Shopping Cart
                </h1>
            <br>
        </div>
    </div>
    <div class="row m-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-7 text-center">
            <table class="table my_custom_table">
                <thead class="my_coustom_thead">
                    <tr>
                        <th colspan='5'>
                            YOUR ITEMS
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for cart_item in cart_items %}
                    <tr>
                        <td>
                            <a href="cart_item.product.get_absolute_url"><img src ="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image" style="width:150px; higtht:150px" ></a>
                        </td>
                        <td class=" text-left ">
                            {{cart_item.product.name}}
                            <br>
                            SKU: {{cart_item.product.id}}
                            <br>
                            Price: {{cart_item.product.price}}
                            <br>
                            Qty : {{cart_item.quantity}} X {{cart_item }}
                        </td>
                        <td>
                            {{cart_item.sub_total}}
                        </td>
                        {% if cart_item.quantity < cart_item.product.stock %}
                        <td>
                            <a href="{% url 'cart_app:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-regular fa-plus custom_icon"></i></a>
                            &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                            &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash-can" style="color: #7b3d3d;"></i></a>
                        </td>
                        {% else %}
                        <td>  
                            &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                        </td>
                        <td>
                            &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash-can" style="color: #7b3d3d;"></i></a>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-9 col-sm-12 col-md-12 col-lg-4 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thread">
                    <tr>
                        CheckOut
                    </tr>
                </thred>
                <tbody>
                    <tr>
                    <td>
                         proceeding with the odder payment 
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                        TOTAL: <strong>{{ total }}</strong>
                    </td>
                </tr>    
                </tbody>
            </table>    
            <div class="mx-auto"> 
                <a href="{% url 'shopapp:allProCat'%}"class="btn btn-secondary btn-block my_custom_button">Continue Shopping </a>
            </div>
        </div>
    </div>
{% endif %}

{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to Shopy
    {% endif %}
{% endblock %}


{% block title %}
    {% if category %}
     {{category.name}}-Shopy Store
    {% else %}
    Shopy
    {% endif %}
{% endblock %}


{% block content %}
{% if category %}

    <div>
        <div class="row my_row_class">
            <div class="mx-auto">
            <p><a href="{% url 'shopapp:products_by_category' c_slug=category.slug %}"> Our Product Collection</a></p>
             </div>
        </div>
    </div>
{% endif %}


<div class="mx-auto">
     {% if category %}
    <img class="my_image" src = "{{category.image.url}}" alt="{{category.name}}">
    
</div><br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}
</div>
   {% else %}
<div>
    <img class="my_image_padding" src="{% static 'img/Banaer.png' %}" alt="our products" width="1220px">
</div><br>
<div>
    <h1 class="text-center my-title"> OUR PRODUCTS COLLECTION </h1>
    <p class="text-justify">  Retail formats (also known as retail formulas) influence the consumer's store choice and addresses the consumer's expectations.
         At its most basic level, a retail format is a simple marketplace, that is; a location where goods and services are exchanged. 
         In some parts of the world, the retail sector is still dominated by small family-run stores, but large retail chains are increasingly
          dominating the sector, because they can exert considerable buying power and pass on the savings in the form of lower prices. 
          Many of these large retail chains also produce their own private labels which compete alongside manufacturer brands. Considerable 
          consolidation of retail stores has changed the retail landscape, transferring power away from wholesalers and into the hands of the
          \ large retail chains.[69] In Britain and Europe, the retail sale of goods is designated as a service activity. The European Service 
          Directive applies to all retail trade including periodic markets, street traders and peddlers.
    </p>
</div>

{% endif %}

<div class="container">
    <div class="row mx-auto">
        {% for product in products.object_list%}
        <div class="my_bottom_margi col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 20rem; heigth: 30rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
            <div class="card-body">
                <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
            </div>       
            </div>
        </div>  
        {% endfor %}
    </div> 
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class= "btn btn-light btn-sm {% if products.number == pg %}active{% endif %}"></a>
            {% endfor %}
        </div>
        {% endif %}
    </div> 
    <br> 
</div>

{% endblock %} 

templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center"> @Copyrigth Shopi pvt Ltd</p>
</div>

templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shopapp:allProCat'%}"><img src="{% static 'img/logo.png' %}" alt="logoimage" width="150px"height="150px">
    </center>
</header>

templates/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">

      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shopapp:allProCat' %}">HOME</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'shopapp:allProCat' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Our-Products
            </a>
            <ul class="dropdown-menu">
                {% for cat in links %}
              <li><a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a></li>{% endfor %}   
            </ul>

          </li
          {% if item_count > 0 %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'cart_app:cart_detail'%}"><i class="fa-solid fa-bag-shopping" style="color: #ff7a7a;"></i>({{item_count}})</a>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex" action="{% url 'search_app:Searchresult'%}" method="get">
        {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
          <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i>  </button>
        </form>
      </div>
    </div>
  </nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   
        {{ product.description|truncatewords:155 }}
        Welcome to Shopy
{% endblock %}


{% block title %}
    {% if category %}
     {{product.name}}-Shopy Store
    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'shopapp:allProCat'%}">Home</a>|<a href="{{product.category.get_url}}">{{product.category}}</a>{{product.name}}</p>
    </div>
</div>

<div class="container">
<br> 
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" alt="{{product.name}}" width="600px" heigth="800px">
        </div>
    </div>
    
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_title">PRODUCT DESCREPTION</p>
            <p class="text-justify my_prod_text">{{product.description}}

                {% if product.stock <= 0 %}
                <p class="text-justify my_prod_text"><b>Out of stock</b></p>
                {% else %}
                <a class="btn btn-secondary" href="{% url 'cart_app:add_cart' product.id %}">Add to Cart</a>
                {% endif %}
        </div>    
    </div>
</div>
</div>
</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
We have variety of products
{% endblock %}
{% block title %}
 Search
{% endblock %}
{% block content%}
    <div>
        <p class="text-center my_serch_text">You have Searched for:<b>"{{query}}"</b></p>
    </div>

    
<div class="container">
    <div class="row mx-auto">
        {% for product in products%}
        <div class="my_bottom_margi col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 20rem; heigth: 30rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
            <div class="card-body">
                <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
            </div>       
            </div>
        </div> 
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 result found</p>
        </div>    
        {% endfor %}
    </div> 
</div>

      
{% endblock %}